// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReasonContext$ReactTemplate = require("./ReasonContext.bs.js");

var Context = ReasonContext$ReactTemplate.CreateContext(/* module */[/* defaultValue */7]);

exports.Context = Context;
/* Context Not a pure module */
