// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var AppContext$ReactTemplate = require("./AppContext.bs.js");

var component = ReasonReact.reducerComponent("Component");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              var send = param[/* send */3];
              return ReasonReact.element(undefined, undefined, Curry._2(AppContext$ReactTemplate.Context[/* Provider */4][/* make */1], param[/* state */1][/* value */0], React.createElement("div", undefined, ReasonReact.element(undefined, undefined, Curry._1(AppContext$ReactTemplate.Context[/* Consumer */5][/* make */1], (function (value) {
                                            return React.createElement("div", undefined, String(value));
                                          }))), React.createElement("button", {
                                      onClick: (function (param) {
                                          return Curry._1(send, /* Increment */0);
                                        })
                                    }, "Increment"), React.createElement("button", {
                                      onClick: (function (param) {
                                          return Curry._1(send, /* Decrement */1);
                                        })
                                    }, "Decrement"))));
            }),
          /* initialState */(function (param) {
              return /* record */[/* value */0];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, param) {
              var value = param[/* value */0];
              if (action) {
                return /* Update */Block.__(0, [/* record */[/* value */value - 1 | 0]]);
              } else {
                return /* Update */Block.__(0, [/* record */[/* value */value + 1 | 0]]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
