// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Component$ReactTemplate = require("./Component.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Component$ReactTemplate.make(/* array */[])), "index");

/*  Not a pure module */
